export const ACTIVITY_ID_1 = 'activity-id-1'
export const ACTIVITY_ID_2 = 'activity-id-2'
export const ACTIVITY_ID_3 = 'activity-id-3'
export const ACTIVITY_ID_4 = 'activity-id-4'
export const ACTIVITY_CODE_1 = 'activity-code-1'
export const ACTIVITY_TITLE_1 = 'activity-title-1'
export const ACTIVITY_TITLE_2 = 'activity-title-2'
export const ACTIVITY_TITLE_3 = 'activity-title-3'
export const ACTIVITY_TITLE_4 = 'activity-title-4'
export const INTERIM_CHECKPOINT_ID_1 = 'interim-checkpoint-id-1'
export const INTERIM_CHECKPOINT_ID_2 = 'interim-checkpoint-id-2'
export const INTERIM_CHECKPOINT_TITLE_1 = 'interim-checkpoint-title-1'
export const INTERIM_CHECKPOINT_TITLE_2 = 'interim-checkpoint-title-2'

export const LEVEL_ID = 'level-id-1'
export const LEVEL_TITLE_1 = 'level-1'
export const PATH_ID = 'path-id-1'

export const REVIEW_STATUS = 'In Review'
